### ISSUE TITLE
pardel

### ISSUE THREAD

**Issue by ItsMexxie** [Matuush/QH-funny#1]
**kolo na tvym péru ha L máš malý péro omg to je docela funny xd moment lmao**
@Matuush 
`true === true`

- [x] do

- [x] your

- [x] mother

**Comment by Matuush** [comment]
this is so me when im eating oyur ssa
penis cum

**Comment by ItsMexxie** [comment]
[free bobucks](https://www.youtube.com/watch?v=Vzt9COfSFqY)
